### ISSUE TITLE
Langs support

### ISSUE THREAD

**Issue by rudolfbruder** [wire-elements/spotlight#75]
Hi,

Is there any way how to use laravel langs and their values in defining for the command name and description?

For me this does not work:
<img width="629" alt="image" src="https://user-images.githubusercontent.com/56951790/165259646-e987a4d8-7a90-4136-b99f-ca34d2473f56.png">

Thank you!

**Comment by jacotijssen** [comment]
Instead of using the name property, you can use the `getName` method. So remove the `protected string $name = "..."` and replace it with something like this:

<img width="630" alt="Schermafbeelding 2022-05-12 om 00 01 05" src="https://user-images.githubusercontent.com/8997440/167954814-014f4b77-e1a5-4585-a43b-e442c03a3a98.png">

**Comment by PhiloNL** [comment]
Haven't tested this but I think you can do:

```php
class ShowJobsTable extends SpotlightCommand
{
    protected string $name;

    public function __construct()
    {
        $this->name = Lang::get('something');
    }
}
```

**Comment by rudolfbruder** [comment]
Thanks works!
